module.exports = [{
    name: '서울시',
    subMenus: [{
        id: 'Jongno-Gu',
        name: '종로구'
    }, {
        id: 'Jung-Gu',
        name: '중구'
    }, {
        id: 'Gangdong-Gu',
        name: '강동구'
    }, {
        id: 'Yongsan-Gu',
        name: '용산구'
    }, {
        id: 'Seongdong-Gu',
        name: '성동구'
    }, {
        id: 'Gwangjin-Gu',
        name: '광진구'
    }, {
        id: 'Dongdaemun-Gu',
        name: '동대문구'
    }, {
        id: 'Jungnang-Gu',
        name: '중랑구'
    }, {
        id: 'Seongbuk-Gu',
        name: '성북구'
    }, {
        id: 'Gangbuk-Gu',
        name: '강북구'
    }, {
        id: 'Dodong-Gu',
        name: '도봉구'
    }, {
        id: 'Nowon-Gu',
        name: '노원구'
    }, {
        id: 'Eunpyeong-Gu',
        name: '은평구'
    }, {
        id: 'Seodaemun-Gu',
        name: '서대문구'
    }, {
        id: 'Mapo-Gu',
        name: '마포구'
    }, {
        id: 'Yangcheon-Gu',
        name: '양천구'
    }, {
        id: 'Gangseo-Gu',
        name: '강서구'
    }, {
        id: 'Guro-Gu',
        name: '구로구'
    }, {
        id: 'Yeongdeungpo-Gu',
        name: '영등포구'
    }, {
        id: 'Dongjak-Gu',
        name: '동작구'
    }, {
        id: 'Gwanak-Gu',
        name: '관악구'
    }, {
        id: 'Seocho-Gu',
        name: '서초구'
    }, {
        id: 'Gangnam-Gu',
        name: '강남구'
    }, {
        id: 'Songpa-Gu',
        name: '송파구'
    }]
}, {
    name: '경기도',
    subMenu: [{
        id: 'Gapyeong-Gun',
        name: '가평군'
    }, {
        id: 'Goyang-Si',
        name: '고양시'
    }, {
        id: 'Gwacheon-Si',
        name: '과천시'
    }, {
        id: 'Guangxi-Si',
        name: '광명시'
    }, {
        id: 'Gwangju-Si',
        name: '광주시'
    }, {
        id: 'Guri-Si',
        name: '구리시'
    }, {
        id: 'Gunpo-Si',
        name: '군포시'
    }, {
        id: 'Kimpo-Si',
        name: '김포시'
    }, {
        id: 'Namyangju-Si',
        name: '남양주시'
    }, {
        id: 'Dongducheon-Si',
        name: '동두천시'
    }, {
        id: 'Bucheon-Si',
        name: '부천시'
    }, {
        id: 'Seongnam-Si',
        name: '성남시'
    }, {
        id: 'Suwon-Si',
        name: '수원시'
    }, {
        id: 'Siheung-Si',
        name: '시흥시'
    }, {
        id: 'Ansan-Si',
        name: '안산시'
    }, {
        id: 'Anseong-Si',
        name: '안성시'
    }, {
        id: 'Anyang-Si',
        name: '안양시'
    }, {
        id: 'Yangju-Si',
        name: '양주시'
    }, {
        id: 'Yangpyeong-Gun',
        name: '양평군'
    }, {
        id: 'Yeoju-Si',
        name: '여주시'
    }, {
        id: 'Yeoncheon-Gun',
        name: '연천군'
    }, {
        id: 'Osan-Si',
        name: '오산시'
    }, {
        id: 'Yongin-Si',
        name: '용인시'
    }, {
        id: 'Uiwang-Si',
        name: '의왕시'
    }, {
        id: 'Uijeongbu-Si',
        name: '의정부시'
    }, {
        id: 'Icheon-Si',
        name: '이천시'
    }, {
        id: 'Paju-Si',
        name: '파주시'
    }, {
        id: 'Pyeongtaek-Si',
        name: '평택시'
    }, {
        id: 'Pocheon-Si',
        name: '포천시'
    }, {
        id: 'Hanam-Si',
        name: '하남시'
    }, {
        id: 'Hwaseong-Si',
        name: '화성시'
    }, {

    }]
}];



