module.exports = [{
    name: '서울시',
    subMenus: [{
        id: 'Gangnam-Gu',
        name: '강남구'
    }, {
        id: 'Gangdong-Gu',
        name: '강동구'
    }, {
        id: 'Gangbuk-Gu',
        name: '강북구'
    }, {
        id: 'Gangseo-Gu',
        name: '강서구'
    }, {
        id: 'Gwanak-Gu',
        name: '관악구'
    }, {
        id: 'Gwangjin-Gu',
        name: '광진구'
    }, {
        id: 'Guro-Gu',
        name: '구로구'
    }, {
        id: 'Geumcheon-Gu',
        name: '금천구'
    }, {
        id: 'Nowon-Gu',
        name: '노원구'
    }, {
        id: 'Dodong-Gu',
        name: '도봉구'
    }, {
        id: 'Dongdaemun-Gu',
        name: '동대문구'
    }, {
        id: 'Dongjak-Gu',
        name: '동작구'
    }, {
        id: 'Mapo-Gu',
        name: '마포구'
    }, {
        id: 'Seodaemun-Gu',
        name: '서대문구'
    }, {
        id: 'Seocho-Gu',
        name: '서초구'
    }, {
        id: 'Seongdong-Gu',
        name: '성동구'
    }, {
        id: 'Seongbuk-Gu',
        name: '성북구'
    }, {
        id: 'Songpa-Gu',
        name: '송파구'
    }, {
        id: 'Yangcheon-Gu',
        name: '양천구'
    }, {
        id: 'Yeongdeungpo-Gu',
        name: '영등포구'
    }, {
        id: 'Yongsan-Gu',
        name: '용산구'
    }, {
        id: 'Eunpyeong-Gu',
        name: '은평구'
    }, {
        id: 'Jongno-Gu',
        name: '종로구'
    }, {
        id: 'Jung-Gu',
        name: '중구'
    }, {
        id: 'Jungnang-Gu',
        name: '중랑구'
    }, {
    }]
}, {
    name: '경기도',
    subMenu: [{
        id: 'Gapyeong-Gun',
        name: '가평군'
    }, {
        id: 'Goyang-Si',
        name: '고양시'
    }, {
        id: 'Gwacheon-Si',
        name: '과천시'
    }, {
        id: 'Guangxi-Si',
        name: '광명시'
    }, {
        id: 'Gwangju-Si',
        name: '광주시'
    }, {
        id: 'Guri-Si',
        name: '구리시'
    }, {
        id: 'Gunpo-Si',
        name: '군포시'
    }, {
        id: 'Kimpo-Si',
        name: '김포시'
    }, {
        id: 'Namyangju-Si',
        name: '남양주시'
    }, {
        id: 'Dongducheon-Si',
        name: '동두천시'
    }, {
        id: 'Bucheon-Si',
        name: '부천시'
    }, {
        id: 'Seongnam-Si',
        name: '성남시'
    }, {
        id: 'Suwon-Si',
        name: '수원시'
    }, {
        id: 'Siheung-Si',
        name: '시흥시'
    }, {
        id: 'Ansan-Si',
        name: '안산시'
    }, {
        id: 'Anseong-Si',
        name: '안성시'
    }, {
        id: 'Anyang-Si',
        name: '안양시'
    }, {
        id: 'Yangju-Si',
        name: '양주시'
    }, {
        id: 'Yangpyeong-Gun',
        name: '양평군'
    }, {
        id: 'Yeoju-Si',
        name: '여주시'
    }, {
        id: 'Yeoncheon-Gun',
        name: '연천군'
    }, {
        id: 'Osan-Si',
        name: '오산시'
    }, {
        id: 'Yongin-Si',
        name: '용인시'
    }, {
        id: 'Uiwang-Si',
        name: '의왕시'
    }, {
        id: 'Uijeongbu-Si',
        name: '의정부시'
    }, {
        id: 'Icheon-Si',
        name: '이천시'
    }, {
        id: 'Paju-Si',
        name: '파주시'
    }, {
        id: 'Pyeongtaek-Si',
        name: '평택시'
    }, {
        id: 'Pocheon-Si',
        name: '포천시'
    }, {
        id: 'Hanam-Si',
        name: '하남시'
    }, {
        id: 'Hwaseong-Si',
        name: '화성시'
    }]
}, {
    name: '부산광역시',
    subMenu: [{
        id: 'Bs-Gangseo-gu',
        name: '강서구'
    }, {
        id: 'Bs-Geumjung-gu',
        name: '금정구'
    }, {
        id: 'Bs-Gijang-gu',
        name: '기장군'
    }, {
        id: 'Bs-Nam-gu',
        name: '남구'
    }, {
        id: 'Bs-Dong-gu',
        name: '동구'
    }, {
        id: 'Bs-Dongnae-gu',
        name: '동래구'
    }, {
        id: 'Bs-Jin-gu',
        name: '진구'
    }, {
        id: 'Bs-buk-gu',
        name: '북구'
    }, {
        id: 'Bs-Sasang-gu',
        name: '사상구'
    }, {
        id: 'Bs-Saha-gu',
        name: '사하구'
    }, {
        id: 'Bs-Seo-gu',
        name: '서구'
    }, {
        id: 'Bs-Suyeong-gu',
        name: '수영구'
    }, {
        id: 'Bs-Yeonje-gu',
        name: '연제구'
    }, {
        id: 'Bs-Yeong-gu',
        name: '영도구'
    }, {
        id: 'Bs-Jung-gu',
        name: '중구'
    }, {
        id: 'Bs-Haeundae-gu',
        name: '해운대구'
    }]
}, {
    name: '대전광역시',
    subMenu: [{
        id: 'Dj-daedeok-gu',
        name: '대덕구'
    }, {
        id: 'Dj-Dong-gu',
        name: '동구'
    }, {
        id: 'Dj-Seo-gu',
        name: '서구'
    }, {
        id: 'Dj-Yuseong-gu',
        name: '유성구'
    }, {
        id: 'Dj-Jung-gu',
        name: '중구'
    }]
}, {
    name: '대구광역시',
    subMenu: [{
        id: 'Dg-Nam-gu',
        name: '남구'
    }, {
        id: 'Dg-Dalseo-gu',
        name: '달서구'
    }, {
        id: 'Dg-Dalseong-gun',
        name: '달성군'
    }, {
        id: 'Dg-Dong-gu',
        name: '동구'
    }, {
        id: 'Dg-Buk-gu',
        name: '북구'
    }, {
        id: 'Dg-Seo-gu',
        name: '서구'
    }, {
        id: 'Dg-Suseong-gu',
        name: '수성구'
    }, {
        id: 'Dg-Jung-gu',
        name: '중구'

    }]
}];



